dbt_estudo:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: ELYATANVENCESLA
      database: ESTUDO
      schema: DBT_ESTUDO
      port: 1433
      windows_login: True
      trust_cert: True